---
title: "Rapport pour le comité d'accompagnement, seconde année de thèse"
author: "Guyliann Engels"
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
output: pdf_document
---

# Avancement de la recherche

## Titre provisoire de la thèse: Adaptations écophysiologiques du scléractiniaire hermatypique _Seriatopora hystrix_ aux changements du milieu (nutriments N et P et stress salin).

Les scléractiniaires hermatypiques bénéficient de symbioses multiples, dont la principale avec les zooxanthelles (du genre _Symbiodinium_), qui lui permettent d'exploiter au mieux les ressources limitées d'un milieu oligothrophe, dont N et P. Cet holobionte corallien, s'il est performant dans ces conditions, se montre également très sensible aux changements du milieu. Parmi les différents stress que subissent les coraux tropicaux, les stress salins sont de plus en plus fréquents et se superposent à d'autres menaces. La salinité peut baisser, suite au passage d'un tempête tropicale, mais elle peut aussi augmenter autour des usines de désalinisation pour la production d'eau douce qui se développent notamment en Mer Rouge. Les _Symbiodinium_ semblent être les symbiotes les plus affectés par ces variations de salinité au sein de l'holobionte corallien.

L'objectif de ce travail est de décrire, quantifier et interpréter l'effet de variation non létales de salinité, de courte durées (moins d'une semaine), ou sur plus long terme (quelques mois) sur le fonctionnement de l'holobionte corallien sur base du modèle _Seriatopora hystrix_. Parmi les effets étudiés, tels la variation de croissance et la formation du squelette, nous porterons une attention particulière à la photosynthèse des _Symbiodinium_ et aux bilans N et P, avant, pendant et après le stress. L'étude se fait en mésocosmes artificiels.


### Chapitre 1: bilan des flux d'azote et de phosphore au niveau de l'holobionte corallien

Les flux d'azote et de phosphore inorganiques, et l'effet de leurs variations dans l'eau, ont déjà fait l'objet de nombreuses études. Cependant, les flux **totaux**, considérant l'azote et le phosphore inorganique **et organique** sont moins étudiés. Nous disposons d'un Seal AA3 équipé pour le dosage de NH3/NH4+, NO3-, NO2-, PO4--- classiques, mais aussi Nt et Pt grâce à un dispositif de digestion et de minéralisation de la matière organique en ligne pour ces deux derniers paramètres. La digestion se fait en milieu acide et oxydant dans un réacteur à U.V. qui permet de minéraliser quasiment toute la matière organique présente dans l'échantillon. Le suivi et l'établissement des bilans se fera, en conditions non stressantes, après mise au point des protocoles de dosage.

**Avancement:** Cette année, nous avons effectué la mise au point de l'[analyseur de nutriments](https://github.com/EcoNum/protocol_seal_aa3) (Seal AA3, dosage des composés azotés et phosphorés). La précision de l'appareil n'est pas satisfaisante entre 0 et 1 $\mu mol/L$ pour NH3 et PO4--- (concentration retrouvée dans nos mésocosmes). L'instrument est actuellement configuré pour être utilisé dans une gamme entre 0 et 10 $\mu mol/L$, ce qui apparaît adéquat pour Nt et Pt. Une mise jour de l'instrument est prévue prochainement (cellule de chemin optique de 5cm au lieu des cellules de 1cm actuelles) pour les chimies qui nécessitent une meilleure précision. De nouveaux tests seront réalisés ensuite. Les mesures de bilans Nt et Pt sur _S. hystrix_ sont prévu pour l'année prochaine.


### Chapitre 2: effets globaux d'un stress salin modéré de courte durée sur l'holobionte corallien

Un dispositif expérimental a été installé dans les mésocosmes pour permettre le contrôle et les variations de salinité dans des bacs expérimentaux secondaires, le tout piloté par ordinateur. Huit respiromètres intermittents sont connectés aux bacs expérimentaux pour mesurer la respiration nocturne et la photosynthèse nette diurne de noutures de coraux en expérience. Les variations de salinité se font par ajout d'eau milliQ ou d'eau sursalée à 50 PSU. Après un test technique nous avons réalisé une première expérience.

Seize boutures ont été suivies de _S. hystrix_ en mésocosme dans les conditions standard (S = 35 PSU, T = 25°C) pendant 32 jours. Un stress salin de 6 jours a été appliqué ensuite, tant en hypersalin (S = 42 PSU, n = 6) qu'en hyposalin (S = 28 PSU, n = 6), un lot témoin restant à salinité de référence (S = 35 PSU, n = 4). La variation et le retour à la normale se sont fait sur une durée de 6 h. La récupération des boutures a ensuite été suivie pendant 28 jours dans les mésocosmes.

Les variables mesurées sont le poids squelettique (via le poids immergé), la photosynthèse nette et la respiration nocturne, l'alcalinité pour réaliser une mesure de croissance squelettique indirecte, la coloration des boutures et divers paramètres physico-chimiques (température, salinité, pH, NH3, NO2-, NO3_ et PO4---).

Durant cette expérience, aucune bouture n'est morte, mais une diminution significative de la croissance (\autoref{growth_plot}) est observée dès le début du stress. Le retour à une croissance normale nécessite plus de 3 semaines après la disparition du stress. Le taux de respiration n'est pas significativement différent de nuit dans les trois conditions. Par contre de jour, une diminution de moitié est observée pour la photosynthèse nette aussi bien dans la condition hyposaline que hypersaline par rapport au contrôle. Comme la photosynthèse nette est la combinaison de la photosynthèse (brute) et de la respiration, il est difficile de déterminer si l'une, l'autre, ou les deux ont changé. Mais comme la respiration nocturne n'a pas changé de manière significative, nous pouvons émettre l'hypothèse que c'est plutôt la photosynthèse des zooxanthelles qui a été la plus affectée. La coloration des boutures a pâli également, confirmant ainsi un impact sur les zooxanthelles. Cette première expérience a confirmé le caractère non létal du stress et aussi que ce sont les zooxanthelles qui sont les plus affectées. Les boutures ont retrouvé des conditions normales à la fin de la phase de récupération.

![Taux de croissance [%/j] au cours du temps [j] avec trois conditions : contrôle (n=4), hypersaline (n=6) et hyposaline (n=6). De plus, trois phases sont mis en avant : avant le stress (Av. stress), stress et récupération. \label{growth_plot}](figure/plot1_red.png){width="65%"}

Le stress hypersalin a produit des effets plus marqués que le stress hyposalin, démontrant ainsi le danger important de l'établissement d'usines de désalinisation à proximité de récifs coralliens tropicaux.

**Avancement:** Cette première expérience fera l'objet d'une publication. Elle doit être suivie d'une seconde expérience sur plus long-terme (chapitre 3). Nous avons particulièrement soigné le suivi de croissance des boutures en mésocosmes  [suivi de la croissance via le poids immergé](https://github.com/EcoNum/coral_growth001), et des outils logiciels ont été mis au point pour faciliter le suivant d'un grand nombre de boutures de manière efficace. Cela sera utile pour toute la suite de la partie expérimentale de ce travail afin d'augmenter le nombre de relicas.


### Chapitre 3: effet d'un stress salin de plusieurs mois sur l'holobionte corallien

Etant donné que ce sont manifestement les zooxanthelles qui sont les plus affectées, une étude plus poussée de la photosynthèse est prévue. Pour se faire, lors de cette seconde expérience, nous étudierons le fonctionnement du photosystème II en particulier à l'aide de fluorimétrie PAM (Waltz mini-PAM I), ainsi que d'un Waltz imaging PAM qui pourra montrer une éventuelle hétérogénéité spatiale à la surface de la bouture au niveau de l'activité photosynthétique des zooxanthelles. Le protocole expérimental sera le même, mais avec 2 à 3 fois plus de boutures (en fonction des disponibilités).

Toujours afin d'étudier la photosynthèse, et notamment pour pouvoir quantifier la photosynthèse brute, nous souhaitons pouvoir utiliser la méthode de shift lumière-obscurité à l'aide d'une [microoptode à oxygène ultra-rapide PyroScience](https://github.com/EcoNum/oxygen_microsensors). Malheureusement, pour l'instant, les essais n'ont pas donnés de résultats utilisables. Comme cette mesure permettrait la détermination directe de la phosynthèse brute, elle est importante dans le cadre de ce travail.

**Avancement:** Nous voulons essayer un autre protocole avec la microoptode oxygène avant de commencer l'expérience. Si nous n'arrivons pas à mesurer la photosynthèse brute de manière suffisamment précise, nous lancerons l'expérience sans cette mesure dans deux ans.


### Chapitre 4: effet d'un stress salin sur les bilans Nt et Pt chez l'holobionte corallien

Ce chapitre visera à approfondir la compréhension des mécanismes qui se déroulent au sein de l'holobionte corallien durant le stress salin, et après, pendant la période de récupération. Nous profiterons ddes données de bilan Nt et Pt du chapitre 1 et de son protocole de mesure et le combinerons avec une expérience de stress salin ciblée, dont le protocole précis reste à définir en fonction des résultats qui seront obtenus dans le chapitre 3.

**Avancement:** Ce travail est prévu en quatrième année de thèse.

A noter que la thèse est prévue pour s’étaler sur 6 ans (assistant) et que ce bilan est réalisé après 1 an et demi. De manière transversale, ces recherches se veulent reproductibles et en accord avec l'Open Science. L'ensemble des notebooks, des rapports, des données est diffusé en libre accès via une [organisation sur Github](https://github.com/EcoNum) (<https://github.com/EcoNum>). Ces notions ont été acquises dans le cadre de ma recherche et de l'enseignement des nouveaux cours de Sciences de données biologiques (remplaçant les cours de Biostatistique).


# Publications et communications scientifiques

## Publications 

Une publication est en préparation concernant le chapitre 2.


## Présentation

- Grosjean Philippe, Engels Guyliann, "Est-il possible d’améliorer encore la courbe d’apprentissage de R au delà de tidyverse? Les packages flow et chart." in "Septièmes rencontres R" , Rennes, France (2018)

- Richir Jonathan, Abadie Arnaud, Borges Alberto, Champenois Willy, Santos Rui, Silva Joa, Walz Steffen, Lejeune Pierre, Engels Guyliann, Gobert Sylvie, "Etude de la photosynthèse de _Posidonia oceanica_ par fluorimétrie modulée" in "Workshop STARECAPMED" , Calvi, France (2018)


## Poster

- Engels Guyliann, Georges Nadège, Conotte Raphaël, Batigny Antoine, Grosjean Philippe, "Réponses écophysiologiques de _Seriatopora hystrix_ (Dana, 1846) lors de stress hypo- et hypersalin" in "Mardi des Chercheurs" , Mons, Belgique (2019)
2018

- Engels Guyliann, Georges Nadège, Conotte Raphaël, Batigny Antoine, Grosjean Philippe, "Ecophysiological responses of _Seriatopora hystrix_ (Dana, 1846) to short-term hypo- and hypersaline stress" in "The 25th Benelux congress of Zoology, “Zoology in the Anthropocene”" , Anvers, Belgique (2018)

- Engels Guyliann, Grosjean Philippe, "Introduction de nouveaux outils (learn, GitHub Classroom,...) dans les cours de Science des données en biologie" in "Septièmes rencontres R" , Rennes, France (2018)
2017


## Activités supplémentaires valorisables pour la formation doctorale

- C.I.B.I.M. (présence) Présence à le conférence annuelle du Centre Interuniversitaire de Biologie Marine à Louvain La Neuve 2017.

- Formation sur le deep learning. Formation d'1/2 journée sur le deep learning durant la septièmes rencontres R (Rennes, France) en 2018.
