---
title: "Rapport pour le comité de thèse"
author: "Guyliann Engels"
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
output:
  pdf_document:
  prettydoc::html_pretty:
    theme: cayman
    highlight: vignette
---

```{r setup, include=FALSE}
#
```

# Compte rendu 

L'étude des réponses écophysiologiques des coraux à des stress par des méthodes non destructives et en mésocosmes (limite du nombre d'individus), requiert l'utilisation de techniques et d'outils particuliers. 

L'apprentissage et la mise au point d'un [analyseur de nutriments](https://github.com/EcoNum/protocol_seal_aa3) (Seal AA3, dosage des composés azotés et phosphorés), d'une [microsonde à oxygène](https://github.com/EcoNum/oxygen_microsensors) (Pyrosciences Sensor, mesure locale de l'oxygène), de chambres respiromètriques (mesure globale de l'oxygène), d'un [fluoromètre](https://github.com/EcoNum/pam_fluorometry) (Imaging-Pam, quantification de la fluorescence émise par la chlorophylle), et enfin du [suivi de la croissance via le poids immergé](https://github.com/EcoNum/coral_growth001) sont les premiers outils et techniques que j'ai utilisé.

[L'impact de la salinité sur les coraux](https://github.com/EcoNum/coral_salinity002) fut la première expérience d'envergure porté sur les coraux avec une partie des outils en cours de mise au point. Les stress salins semblent avoir affecté directement les zooxanthelles. Afin de vérifier cette hypothèse, une seconde expérience sur l'impact de la salinité va débuter avec l'objectif de quantifier les zooxanthelles. 

De manière transversale, ces recherches se veulent reproductibles et en accord avec l'Open Science. L'ensemble des notebbok, des rapports, des données sont diffusés en libre accès via une [organisation sur Github](https://github.com/EcoNum). J'ai du apprendre ces notions pour ma recherche et pour l'enseignement des nouveaux cours de Sciences de données biologiques (remplacent des cours de Biostatistique).


# Publications 

Cette section est générée via la [Dépôt institutionnel de l’Université de Mons](http://di.umons.ac.be/catalogue.aspx) (DI-UMONS) et se trouve en annexe de ce document.

# Liste des activités supplémentaires.

- Formation pédagogique du Corps Scientifique oganisée par le Service d'Appui Pédagogique de l'Université de Mons.

Formation obligatoire pour tous les assistants de l'Université de MONS. Cette formation n'est cependant pas créditée et s'est déroulée durant l'année académique 2017-2018. 

- C.I.B.I.M. (présence)

Présence à le conférence annuelle du Centre Interuniversitaire de Biologie Marine à Louvain La Neuve 2017.

- Formation sur le deep learning 

Formation d'1/2 journée sur le deep learning durant la septièmes rencontres R (Rennes, France)
